/*
# Create investigations table for CybroatriX Email Forensics

1. New Tables
- `investigations` — stores email forensic analysis results
  - `id` (text, primary key) — investigation ID generated by the app
  - `filename` (text) — original EML file name
  - `uploaded_at` (timestamptz) — when the file was uploaded
  - `analyzed_at` (timestamptz) — when analysis completed
  - `status` (text) — completed | partial | failed
  - `sender` (text) — sender email address
  - `recipient` (text) — recipient email address
  - `subject` (text) — email subject
  - `threat_score` (integer) — 0-100 risk score
  - `threat_level` (text) — LOW | MEDIUM | HIGH | CRITICAL
  - `summary` (text) — AI executive summary
  - `indicator_counts` (jsonb) — counts of IPs, domains, URLs, attachments
  - `result_data` (jsonb) — full analysis result JSON
  - `created_at` (timestamptz) — record creation timestamp

2. Security
- Enable RLS on `investigations`.
- Single-tenant app with no sign-in screen: allow anon + authenticated CRUD
  since investigation data is intentionally shared/public for the forensic platform.
*/

CREATE TABLE IF NOT EXISTS investigations (
  id text PRIMARY KEY,
  filename text NOT NULL,
  uploaded_at timestamptz,
  analyzed_at timestamptz,
  status text DEFAULT 'completed',
  sender text,
  recipient text,
  subject text,
  threat_score integer DEFAULT 0,
  threat_level text DEFAULT 'LOW',
  summary text,
  indicator_counts jsonb DEFAULT '{}',
  result_data jsonb,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE investigations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_investigations" ON investigations;
CREATE POLICY "anon_select_investigations" ON investigations FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_investigations" ON investigations;
CREATE POLICY "anon_insert_investigations" ON investigations FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_investigations" ON investigations;
CREATE POLICY "anon_update_investigations" ON investigations FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_investigations" ON investigations;
CREATE POLICY "anon_delete_investigations" ON investigations FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_investigations_created_at ON investigations (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_investigations_threat_level ON investigations (threat_level);
